# Generated by Django 2.1 on 2018-10-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeration',
            name='confirmpassword',
            field=models.CharField(default='', max_length=200),
        ),
    ]
