# Generated by Django 2.1 on 2018-10-31 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_registeration_confirmpassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeration',
            old_name='email',
            new_name='username',
        ),
    ]
