# Generated by Django 2.1 on 2018-10-31 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_auto_20181031_1056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registeration',
        ),
    ]
