# Generated by Django 2.1 on 2018-10-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signup', '0004_delete_registeration'),
    ]

    operations = [
        migrations.CreateModel(
            name='registeration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('confirmpassword', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
