# Generated by Django 2.1 on 2018-10-31 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_registeration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeration',
            old_name='confirmpassword',
            new_name='dconfirmpassword',
        ),
        migrations.RenameField(
            model_name='registeration',
            old_name='firstname',
            new_name='dfirstname',
        ),
        migrations.RenameField(
            model_name='registeration',
            old_name='lastname',
            new_name='dlastname',
        ),
        migrations.RenameField(
            model_name='registeration',
            old_name='password',
            new_name='dpassword',
        ),
        migrations.RenameField(
            model_name='registeration',
            old_name='username',
            new_name='dusername',
        ),
    ]
